### ISSUE TITLE
about dataset.py line 94

### ISSUE THREAD

**Issue by pengfeidip** [xiongzihua/pytorch-YOLO-v1#13]
你好, 
以下为源码, 我添加了注释, 问题在注释里
```
boxes /= torch.Tensor([w,h,w,h]).expand_as(boxes)
img = self.BGR2RGB(img)
img = self.subMean(img,self.mean) 

# 因为网络输入要求, 所以缩放到固定尺寸, 但是在这之后
#  难道不应该再调整一下 bboxes的值吗.. 
#  此时的img和bboxes已经不匹配了(我特意看了self.encoder, 也没有类似的操作)
img = cv2.resize(img,(self.image_size,self.image_size))
target = self.encoder(boxes,labels)
```

**Comment by JJZHK** [comment]
boxes /= torch.Tensor([w,h,w,h]).expand_as(boxes)这一句boxes的尺寸都已经被归一化了。此时boxes已经是相对位置了，跟img具体的大小已经没有任何关系。

**Comment by JJZHK** [comment]
> 你好,
> 以下为源码, 我添加了注释, 问题在注释里
> 
> ```
> boxes /= torch.Tensor([w,h,w,h]).expand_as(boxes)
> img = self.BGR2RGB(img)
> img = self.subMean(img,self.mean) 
> 
> # 因为网络输入要求, 所以缩放到固定尺寸, 但是在这之后
> #  难道不应该再调整一下 bboxes的值吗.. 
> #  此时的img和bboxes已经不匹配了(我特意看了self.encoder, 也没有类似的操作)
> img = cv2.resize(img,(self.image_size,self.image_size))
> target = self.encoder(boxes,labels)
> ```

boxes /= torch.Tensor([w,h,w,h]).expand_as(boxes)这一句boxes的尺寸都已经被归一化了。此时boxes已经是相对位置了，跟img具体的大小已经没有任何关系。

**Comment by pengfeidip** [comment]
> > 你好,
> > 以下为源码, 我添加了注释, 问题在注释里
> > ```
> > boxes /= torch.Tensor([w,h,w,h]).expand_as(boxes)
> > img = self.BGR2RGB(img)
> > img = self.subMean(img,self.mean) 
> > 
> > # 因为网络输入要求, 所以缩放到固定尺寸, 但是在这之后
> > #  难道不应该再调整一下 bboxes的值吗.. 
> > #  此时的img和bboxes已经不匹配了(我特意看了self.encoder, 也没有类似的操作)
> > img = cv2.resize(img,(self.image_size,self.image_size))
> > target = self.encoder(boxes,labels)
> > ```
> 
> boxes /= torch.Tensor([w,h,w,h]).expand_as(boxes)这一句boxes的尺寸都已经被归一化了。此时boxes已经是相对位置了，跟img具体的大小已经没有任何关系。

...确实, 没注意这一点!, 多谢
