### ISSUE TITLE
请问关于vgg16_bn版本的performance

### ISSUE THREAD

**Issue by pengfeidip** [xiongzihua/pytorch-YOLO-v1#15]
**背景**
预训练的vgg16_bn

我在110个epoch后mAP只有52%，而且很难再提升；但是通过预训练的resnet50,50个epoch就有67%，不知道问题出在哪。。

**Comment by pengfeidip** [comment]
我好像知道了，好像是因为在net.py构建VGG16_bn的时候，第一个卷积层的步长为2。等于448的图像一进来就下采样....应该是这样的原因...
![image](https://user-images.githubusercontent.com/23066797/50537268-72c5a200-0b98-11e9-80f4-b82a4870c993.png)

**Comment by abeardear** [comment]
我最开始实验的情况也差不多吧，我也不太了解~多跑几次，改改网络

**Comment by abeardear** [comment]
对了，其实我这个实现丢弃了全连接层，resnet_yolo是这样的，可能VGG16_bn也要把全连接层去掉，用全卷积方式输出^_^ @pengfeidip

**Comment by pengfeidip** [comment]
@xiongzihua  ok 多谢，我现在没在弄这个了，以后有时间再来试试，谢谢你的分享代码！
