### ISSUE TITLE
疑问：关于target的encoder部分

### ISSUE THREAD

**Issue by 981680703** [xiongzihua/pytorch-YOLO-v1#2]
似乎是把box的坐标encode成相对与box中心所在网格的相对位置
![2018-05-02 22-52-26](https://user-images.githubusercontent.com/36734949/39530652-fcc91996-4e5b-11e8-8217-07d78e3d8bc7.png)

但是计算IOU时怎么可以直接把这个target放进去？
![2018-05-02 22-54-05](https://user-images.githubusercontent.com/36734949/39530699-121f00f8-4e5c-11e8-8336-6560342b0aff.png)

**Comment by xiongzihua** [comment]
这里好像是有问题！！计算IOU的时候box_target中心应该转换成实际的中心。。
