### ISSUE TITLE
您能提供一下预训练好的模型文件吗，谢谢！

### ISSUE THREAD

**Issue by KaijieL** [xiongzihua/pytorch-YOLO-v1#28]
您能提供一下预训练好的模型文件吗，谢谢！
邮箱：986698995@qq.com

**Comment by 2017TJM** [comment]
> 您能提供一下预训练好的模型文件吗，谢谢！
> 邮箱：[986698995@qq.com](mailto:986698995@qq.com)

可以和我交流下QQ:2949465671

**Comment by yangxb323** [comment]
您能提供一下预训练好的模型文件吗，谢谢！
邮箱：1519959584@qq.com
