### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by omg777** [xiongzihua/pytorch-YOLO-v1#3]
```
    num_faces = int(splited[1])
IndexError: list index out of range
```

I changed file_root and test_root in train.py
then run train.py, the error occurs.

and I want to ask you what is the role of dataset.py.
thanks for your nice work!

**Comment by xiongzihua** [comment]
dataset.py is a custom dataloader, it is common in pytorch.

`with open(list_file) as f:
            lines  = f.readlines()

        for line in lines:
            splited = line.strip().split()
            self.fnames.append(splited[0])
            num_faces = int(splited[1])`

list_file is anno.txt like this:
image0.jpg 2 x1 y1 w1 h1 1 x2 y2 w2 h2 1
image1.jpg 1 x1 y1 w1 h1 1
