### ISSUE TITLE
yoloLoss的组成部分中contain_loss的可疑之处

### ISSUE THREAD

**Issue by CF-chen-feng-CF** [xiongzihua/pytorch-YOLO-v1#30]
contain_loss = F.mse_loss(box_pred_response[:,4],box_target_response_iou[:,4],size_average=False)
box_pred_response[:,4]代表的是iou值较大的预测得分，
box_target_response_iou[:,4]代表iou的值，
利用这两个信息求loss是什么意思勒，希望能得到作者的解惑。
我认为这行语句应该改为以下形式更为妥当：
contain_loss =
F.mse_loss(box_pred_response[:,4],box_target_response[:,4],size_average=False)
这只是我个人看法，还是希望能得到作者和广大码农的帮助

**Comment by wanxinzzz** [comment]
[x,y,w,h,c]中的c预测的是预测框与ground truth之间的IOU，而不仅是预测为物体的概率
