### ISSUE TITLE
key errors: unexpected keys in state_dict

### ISSUE THREAD

**Issue by lizilongcn** [xiongzihua/pytorch-YOLO-v1#4]
https://github.com/xiongzihua/pytorch-YOLO-v1/blob/0e5776a15e63f6d811c61a1b08f382bc41cff8c0/predict.py#L146

Hi，zihua:

after training , I run `predict.py`, then I get an error shows that keys are mismatch. Could you help me solve this bug? Thanks ~

The errror information:
```
RuntimeError: Error(s) in loading state_dict for VGG:
Missing key(s) in state_dict: "features.0.weight", "features.0.bias"...
Unexpected key(s) in state_dict: "module.features.0.weight", "module.features.0.bias"...

```

**Comment by xiongzihua** [comment]
Hi, I think you use DataParallel for mutil GPU train, you can change net = torch.nn.DataParallel(model, device_ids=[0, 1,]) in predict.py. You can also replace state_dict's key like [this](https://github.com/xiongzihua/FashionAI_Keypoint/blob/master/fusemodel/train_argmax.py). from line 65 to 81
