### ISSUE TITLE
为什么结果的置信度这么低呢？ 0.2，0.3这样子？

### ISSUE THREAD

**Issue by feifeiwei** [xiongzihua/pytorch-YOLO-v1#5]

**Comment by xiongzihua** [comment]
因为置信度是pred_iou*cls_prob，比如0.7*0.7=0.49，就会比较小。

另外，预测框与真实框的cxcy被编码为(cxcy-cell_leftup)/cell_size，这是为了使其范围在0-1之间。这样把两框之间距离增加了，所以计算的iou会小于实际情况，普遍偏小一点。

所以置信度会低一点，不过应该不影响筛选正确预测框。

**Comment by feifeiwei** [comment]
好的， 感谢回复！

**Comment by Bigwode** [comment]
@xiongzihua 感觉这么计算confidence不合适 吧。
